# Model Decorte Esco
# Data Decorte Esco
model:
  embedding_model_finetuning: "all-mpnet-base-v2"
  embedding_model_transformation: "ElenaSenger/career-path-representation-mpnet-decorte-esco"
data:
  data_type: "decorte_esco"
output:
  path_embedding_model: "./output/all-mpnet-base-v2_finetuned_decorte_esco" #adjust if needed
  path_transformation_matrix: "./output/matrix_T_decorte_esco.npy"
  path_linear_transformation_errors: "./output/matrix_T_errors_decorte_esco.json"

