# Model Karrierewege CP
# Data Karrierewege CP
model:
  embedding_model_finetuning: "all-mpnet-base-v2"
  embedding_model_transformation: "ElenaSenger/career-path-representation-mpnet-karrierewege-cp"
data:
  data_type: "karrierewege_cp"
output:
  path_embedding_model: "./output/all-mpnet-base-v2_finetuned_karrierewege_cp" #adjust if needed
  path_transformation_matrix: "./output/matrix_T_karrierewege_cp.npy"
  path_linear_transformation_errors: "./output/matrix_T_errors_karrierewege_cp.json"
