# Model Karrierewege OCC
# Data Karrierewege OCC
model:
  embedding_model_finetuning: "all-mpnet-base-v2"
  embedding_model_transformation: "ElenaSenger/career-path-representation-mpnet-karrierewege-occ"
data:
  data_type: "karrierewege_occ"
output:
  path_embedding_model: "./output/all-mpnet-base-v2_finetuned_karrierewege_occ" #adjust if needed
  path_transformation_matrix: "./output/matrix_T_karrierewege_occ.npy"
  path_linear_transformation_errors: "./output/matrix_T_errors_karrierewege_occ.json"
